### ISSUE TITLE
Release 0.5.0 Error

### ISSUE THREAD

**Issue by ralf-e** [znanev/ATC_MiThermometer#8]
Release 0.5.0. does not work here, tried several times. Flashed back to 0.4.0 and everything is ok again.
![grafik](https://user-images.githubusercontent.com/3521615/101065211-2b6e9a00-3595-11eb-95b9-b0225cbd96cb.png)

**Comment by znanev** [comment]
@ralf-e Thanks for reporting this issue. It seems that waiting in deep sleep is causing troubles, will revert to the previous one when I commit some other changes.

**Comment by znanev** [comment]
@ralf-e You can use [Release 0.6.0](https://github.com/znanev/ATC_MiThermometer/releases/tag/0.6.0) now, removed the deep sleep experimental code that bugged the display.

**Comment by ralf-e** [comment]
flashed, currently works with v0.6.0
